Update seg_tta.py
When using the - tta command for multi-scale prediction, and the test set is not annotated, although format_only has been set true in test_evaluator,  but SegTTAModel class  still threw error 'AttributeError: 'SegDataSample' object has no attribute '_gt_sem_seg''. The reason is SegTTAModel  didn't determine if there were annotations in the dataset, so I added the code to make the judgment and let the program run normally on my computer.